# .streamlit/secrets.toml

SUPABASE_URL = "https://jvkfznrnekhfyznrkshn.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2a2Z6bnJuZWtoZnl6bnJrc2huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1MTY1NjcsImV4cCI6MjA4MzA5MjU2N30.mtXLxf9_jfHVtoyHB7N1roeR45PQSKxoDui0Q7WvcVc"